FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3.7-bionic-run

RUN install_packages gcc musl-dev zlib1g-dev libjpeg-dev libfreetype6-dev

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install --upgrade pip
RUN pip3 install wheel
RUN pip3 install -r requirements.txt
 
COPY . ./

RUN chmod +x start.sh

CMD [ "/bin/bash", "/app/start.sh"]

# For local development; add a v to de
######de-cmd-live=balena-idle