FROM balenalib/raspberrypi3-ubuntu-python:3.7-bionic-build

RUN install_packages libfreetype6-dev

# Defines our working directory in container
WORKDIR /app
 
# This will copy all files in our root to the working directory in the container (including start.sh)
COPY . ./

RUN chmod +x start.sh

CMD [ "/bin/bash", "/app/start.sh"]

# For local development; add a v to de
######de-cmd-live=balena-idle