FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu:focal

RUN install_packages bluetooth bluez libbluetooth-dev libudev-dev golang

# Defines our working directory in container
WORKDIR /app

# This will copy all files in our root to the working directory in the container
COPY . ./

RUN chmod +x start.sh

CMD [ "/bin/bash", "/app/start.sh"]

# For local development; add a v to de
######de-cmd-live=balena-idle